require("oli.plugins-setup")
require("oli.core.options")
require("oli.core.keymaps")
require("oli.core.colorscheme")
require("oli.plugins.comment")
require("oli.plugins.nvim-tree")
require("oli.plugins.lualine")
require("oli.plugins.telescope")
require("oli.plugins.nvim-cmp")
require("oli.plugins.lsp.mason")
require("oli.plugins.lsp.lspsaga")
require("oli.plugins.lsp.lspconfig")
require("oli.plugins.lsp.null-ls")
require("oli.plugins.autopairs")
require("oli.plugins.treesitter")
require("oli.plugins.gitsigns")

